language: python

python:
  - 2.7

env:
  - DJANGO=1.5.5
  - DJANGO=1.6.1

branches:
  except:
    - master

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd tests && ./manage.py test testapp
