language: python

python:
  - 2.7

env:
  - DJANGO=1.5.5 TEST=testapp
  - DJANGO=1.6.1 TEST=testapp.tests

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test $TEST
